### ISSUE TITLE
NSFW Project

### ISSUE THREAD

**Issue by dreamsoftech** [sswangg/the-warden#1]
Hi @sswangg 
I am a CTO at WALTB and we are building video chatting application.
In our application, we need to implement NSFW processing and I need your help.
I tried yahoo NSFW engine and it's a little slow than we need.
We need to process image within 30 ~ 50 ms but yahoo engine takes 70 ~ 80ms.
So I tried to find alternative solution and I am reaching out to you.
Can we schedule a call and discuss the project?
My email is andrew@waltb.co.
My github handle is dreamsoftech

Thanks,
Andrew

**Comment by sswangg** [comment]
Go away ew person illega;l distribution minor stuff idk

**Comment by sswangg** [comment]
<img width="780" alt="Screen Shot 2021-10-22 at 10 08 08 PM" src="https://user-images.githubusercontent.com/54683098/138538496-6940d04a-1d3c-4d3e-8918-03fd83c010e7.png">
Spam
